services:
  jsp-app:
    build: 
      context: .
      dockerfile: Dockerfile.paulo
    volumes:
      - ./target:/usr/local/tomcat/webapps/
    depends_on:
      - postgres
    ports:
      - 8080:8080

  postgres:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5431:5432
    volumes:
      - ${USERPROFILE}/Documentos/Docker/teste/PostgreSQL/baseapp:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080